### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by sxh1136** [jondeaton/PhaMers#5]
Hi there, I'm trying to run Phamers but i keep getting this error. Any idea how to fix this?

./phamer.py -in /home/ubuntu/aqua_amr/software/PhaMers/phage -data data --debug --equalize_reference                                       ✔
[2020-09-25 18:09:27,312][INFO][<module>] - Loading data into scoring object...
[2020-09-25 18:09:27,312][INFO][load_data] - Calculating features of: Phage_frag_refseq_post2018.fasta
[2020-09-25 18:10:34,150][INFO][load_data] - Saving features to /home/ubuntu/aqua_amr/software/PhaMers/phage/Phage_frag_refseq_post2018_features.csv...
[2020-09-25 18:10:36,124][DEBUG][screen_by_length] - 8407 of 8411 contigs > 5.00 kbp
Traceback (most recent call last):
  File "./phamer.py", line 573, in <module>
    scorer.equalize_reference_data()
  File "./phamer.py", line 164, in equalize_reference_data
    num_positive = self.positive_data.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by sxh1136** [comment]
Mistake on my behalf, running from scripts directory rather than the directory above
